version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: invoice-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: invoice_parser
    ports:
      - "3306:3306"
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - ./.data/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: invoice-phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"
    depends_on:
      - mysql